version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3 
  aws-eks: circleci/aws-eks@0.2.3

jobs:
  build-frontend:
    docker:
        - image: circleci/node:16.13.0
    working_directory: ~/project

    steps:
        - checkout
        - run:
            name: Show current branch
            command: echo ${CIRCLE_BRANCH}
        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
        - run:
            name: Install local dependencies
            command: npm install
        - save_cache:
            key: v1-dependencies-{{ checksum "package.json" }}
            paths:
                - node_modules
        - run:
            name: Install local dependencies
            command: 
              npm update
        - run:
            name: Build app
            command: |
              sudo npm i
              npm run build
workflows:
  default:
      jobs:
        - build-frontend
